### PR TITLE
Made reports/ part of the project excluding its contents

### PR DESCRIPTION
**Pull request by enricocarraro**
The reports/ directory is needed for the server to work correctly.
When I first tried to run the server, it didn't create the folder automatically, and I was getting some errors because of it; this should solve the problem.

### CODE REVIEW

**Comment by salcho** [comment]
Hi Enrico! Thanks so much for your PR! Versioning the reports folder would have the side effect of storing a bunch of reports on this repo, which isn't great. 

Instead, would you mind adding a bit of code to app.js that makes sure that the folder is created at startup (but doesn't rewrite it if it's already there)?

**Review by salcho — CHANGES_REQUESTED** [review]
Please see my comment on the PR!

**Comment by enricocarraro** [comment]
Hi, Sal! The change I'm proposing would store just the `.gitkeep` file, the other contents of the directory would be ignored.
It's completely okay for me to rethink the solution if you think it's not suitable.

**Comment by salcho** [comment]
Sorry I misinterpreted this before! Thanks for your PR!

**Pull request merged**
